version: '2'
services:
  zookeeper:
    volumes:
      - /mnt/zookeeper/data:/data
      - /mnt/zookeeper/datalog:/datalog
  kafka:
    volumes:
      - /mnt/kafka:/var/lib/kafka/data
  flask:
    volumes: 
      - ./api:/var/api
  postgres:
    volumes:
      - ./build/postgres/resources/init.sql:/docker-entrypoint-initdb.d/init.sql
  # faust:
  #   volumes:
  #     - ./faust:/var/faust_app/
  #     - ./test_data/:/faust_app/test_data
  #     - /mnt/faust_data:/data/
