version: '2'
services:
  zookeeper:
    volumes:
      - /mnt/zookeeper/data:/data
      - /mnt/zookeeper/datalog:/datalog
  kafka:
    volumes:
      - /mnt/kafka:/var/lib/kafka/data
  flask:
    volumes: 
      - ./api:/var/api
  postgres:
    volumes:
      - ./build/postgres/resources/schema.sql:/docker-entrypoint-initdb.d/1-schema.sql
      - ./build/postgres/resources/data.sql:/docker-entrypoint-initdb.d/2-data.sql
      - ./build/postgres/resources/user.sql:/docker-entrypoint-initdb.d/3-user.sql
      - postgres_data:/var/lib/postgresql/data/

  faust:
    volumes:
      - ./faust:/var/faust_app/
      - ./test_data/:/faust_app/test_data
      - /mnt/faust_data:/data/

volumes:
  postgres_data:
